### ISSUE TITLE
constraining shapes leave some global state

### ISSUE THREAD

**Issue by nschloe** [krober10nd/SeismicMesh#102]
When trying to mesh the L-shape and something else one after another, SM will error out.

MWE:
```python
import numpy
import SeismicMesh


def l_shape():
    h = 0.1
    bbox = (0.0, 1.0, 0.0, 1.0)

    bbox0 = (0.0, 1.0, 0.0, 0.5)
    rect0 = SeismicMesh.Rectangle(bbox0)

    bbox1 = (0.0, 0.5, 0.0, 1.0)
    rect1 = SeismicMesh.Rectangle(bbox1)

    corners = SeismicMesh.geometry.corners

    def union(x):
        return numpy.minimum.reduce([rect0.eval(x), rect1.eval(x)])

    pfix = numpy.vstack((corners(bbox0), corners(bbox1)))

    points, cells = SeismicMesh.generate_mesh(
        bbox=bbox,
        domain=union,
        edge_length=h,
        pfix=pfix,
        verbose=0,
    )


def ball():
    h = 0.1
    bbox = (-1.0, 1.0, -1.0, 1.0, -1.0, 1.0)

    def ball(x):
        return numpy.sqrt(x[:, 0] ** 2 + x[:, 1] ** 2 + x[:, 2] ** 2) - 1.0

    points, cells = SeismicMesh.generate_mesh(
        bbox=bbox, h0=h, domain=ball, edge_length=h, verbose=False
    )
    points, cells = SeismicMesh.sliver_removal(
        points=points, bbox=bbox, h0=h, domain=ball, edge_length=h, verbose=False
    )


l_shape()
ball()
```
```
Constraining 8 fixed points..
Constraining 8 fixed points..
Traceback (most recent call last):
  File "y.py", line 47, in <module>
    ball()
  File "y.py", line 38, in ball
    points, cells = SeismicMesh.generate_mesh(
  File "/home/nschloe/.local/lib/python3.8/site-packages/SeismicMesh/generation/mesh_generator.py", line 399, in generate_mesh
    fh, p, extents = _initialize_points(dim, geps, bbox, fh, fd, h0, opts, pfix, comm)
  File "/home/nschloe/.local/lib/python3.8/site-packages/SeismicMesh/generation/mesh_generator.py", line 756, in _initialize_points
    fh, p, extents = _generate_initial_points(
  File "/home/nschloe/.local/lib/python3.8/site-packages/SeismicMesh/generation/mesh_generator.py", line 741, in _generate_initial_points
    p = np.vstack(
  File "<__array_function__ internals>", line 5, in vstack
  File "/home/nschloe/.local/lib/python3.8/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3
```

**Comment by krober10nd** [comment]
This is an odd one for me. I replicated the behavior. Maybe I'm confused something in the Python language or misunderstanding garbage collection. 

When the function exits, the garbage should be collected, no? And then upon the next call the default options should be set and then the kwargs should be parsed. Guess that clearly isn't happening.

**Comment by nschloe** [comment]
Without looking at the code, I'm smelling [mutable default arguments](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments).

**Comment by krober10nd** [comment]
Yes, that's good intuition. This was indeed the problem and as a result I moved the dictionaries that define default options *inside* their respective functions (in the pull request referenced above). This seemingly fixes the errors. 

Actually, this helped me catch some gotcha calls on the README examples (where I didn't pass the bbox to the `sliver_removal` for instance).

**Comment by krober10nd** [comment]
Okay, the fix for this was merged in and your MWE now actually works. After I finish the other improvement to the API, I'll release a new version.
