### ISSUE TITLE
ModuleNotFoundError: No module named '_fast_geometry'

### ISSUE THREAD

**Issue by Zhang-Ziwen** [krober10nd/SeismicMesh#237]
I successfully installed SeismicMesh by .whl , but when importing SeismicMesh in spyder, the following problems occur：
>>>[autoreload of SeismicMesh.decomp failed: Traceback (most recent call last):
  File "D:\Python\Python\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "D:\Python\Python\lib\site-packages\IPython\extensions\autoreload.py", line 394, in superreload
    module = reload(module)
  File "D:\Python\Python\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "D:\Python\Python\lib\importlib\__init__.py", line 159, in reload
    raise ImportError(msg.format(parent_name),
ImportError: parent 'SeismicMesh' not in sys.modules
]

>>> File "D:\Python\Python\lib\site-packages\SeismicMesh\geometry\__init__.py", line 1, in <module>
    from _fast_geometry import (

>>>ModuleNotFoundError: No module named '_fast_geometry'

**Comment by krober10nd** [comment]
Can you confirm that you've installed a version of cgal >= 5.0?

Older versions of pip may hide the installation error.

**Comment by Zhang-Ziwen** [comment]
Yes，I have installed the package named cgal 5.5.1.post202210191030 by pip.
Do I need to reinstall it by other ways?

**Comment by krober10nd** [comment]
The error occurs because the CPP modules did not compile correctly. Please use `python setup.py develop` in the package directory and see what the error is.
